src/KekRozsak/FrontBundle/Entity/Book.php
<?php

namespace KekRozsak\FrontBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints as DoctrineAssert;
use Doctrine\Common\Collections\ArrayCollection;

use KekRozsak\SecurityBundle\Entity\User;

/**
 * KekRozsak\FrontBundle\Entity\Book
 *
 * @ORM\Entity
 * @ORM\Table(name="books")
 *
 * @DoctrineAssert\UniqueEntity(fields={"author", "title", "year"})
 */
class Book
{
    public function __construct()
    {
        $this->copies = new ArrayCollection();
        $this->wouldBorrow = new ArrayCollection();
        $this->wouldBuy = new ArrayCollection();
    }

    /**
     * The ID of the Book
     *
     * @var integer $id
     *
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * The copies available for this Book
     *
     * @var Doctrine\Common\Collections\ArrayCollection $copies
     *
     * @ORM\OneToMany(targetEntity="BookCopy", mappedBy="book")
     */
    protected $copies;

    /**
     * Remove a copy
     *
     * @param  KekRozsak\FrontBundle\Entity\BookCopy $copy
     * @return Book
     */
    public function removeCopy(BookCopy $copy)
    {
        $this->copies->removeElement($copy);
    }

    /**
     * Get copies
     *
     * @return Doctrine\Common\Collections\ArrayCollection
     */
    public function getCopies()
    {
        return $this->copies;
    }

    /**
     * Get the copies of this Book those are borrowed by someone
     *
     * @return Doctrine\Common\Collections\ArrayCollection
     */
    public function getCopiesBorrowed()
    {
        return $this->copies->filter(function($copy) {
                return ($copy->getBorrower() !== null);
            });
    }

    /**
     * Get the copies of this Book those are borrowed by $user
     *
     * @param  KekRozsak\SecurityBundle\Entity\User        $user
     * @return Doctrine\Common\Collections\ArrayCollection
     */
    public function getCopiesBorrowedByUser(User $user)
    {
        return $this->copies->filter(function($copy) use ($user) {
                return ($copy->getBorrower() == $user);
            });
    }

    /**
     * Get the copies of this Book those are borrowed by $user, but marked as
     * returned
     *
     * @param  KekRozsak\SecurityBundle\Entity\User        $user
     * @return Doctrine\Common\Collections\ArrayCollection
     */
    public function getCopiesBorrowedReturnedByUser(User $user)
    {
        return $this->copies->filter(function($copy) use ($user) {
                return ($copy->getBorrower() == $user) && ($copy->isBorrowerReturned());
            });
    }

    /**
     * Get all the borrowable copies of this Book
     *
     * @return Doctrine\Common\Collections\ArrayCollection
     */
    public function getCopiesBorrowable()
    {
        return $this->copies->filter(function($copy) {
            return $copy->isBorrowable();
        });
    }

    /**
     * Get $user's copies of this Book
     *
     * @param  KekRozsak\SecurityBundle\Entity\User        $user
     * @return Doctrine\Common\Collections\ArrayCollection
     */
    public function getUsersCopies(User $user)
    {
        return $this->copies->filter(function ($copy) use ($user) {
                return ($copy->getOwner() == $user);
            });
    }

    /**
     * Get $user's borrowable copies of this Book
     *
     * @param  KekRozsak\SecurityBundle\Entity\User        $user
     * @return Doctrine\Common\Collections\ArrayCollection
     */
    public function getUsersCopiesBorrowable(User $user)
    {
        return $this->copies->filter(function($copy) use ($user) {
                return (($copy->getOwner() == $user) && $copy->isBorrowable());
            });
    }

    /**
     * Get $user's buyable copies of this Book
     *
     * @param  KekRozsak\SecurityBundle\Entity\User        $user
     * @return Doctrine\Common\Collections\ArrayCollection
     */
    public function getUsersCopiesBuyable(User $user)
    {
        return $this->copies->filter(function($copy) use ($user) {
                return (($copy->getOwner() == $user) && $copy->isBuyable());
            });
    }

    /**
     * The author of the Book
     *
     * @var string $author
     *
     * @ORM\Column(type="string", length=100, nullable=false)
     */
    protected $author;

    /**
     * Set author
     *
     * @param  string $author
     * @return Book
     */
    public function setAuthor($author)
    {
        // TODO: Check if null!
        $this->author = $author;

        return $this;
    }

    /**
     * Get author
     *
     * @return string
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * The title of the Book
     *
     * @var string $title
     *
     * @ORM\Column(type="string", length=100, nullable=false)
     */
    protected $title;

    /**
     * Set title
     *
     * @param  string $title
     * @return Book
     */
    public function setTitle($title)
    {
        // TODO: Check if null!
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * The Book's year of publication
     *
     * @var integer $year
     *
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $year;

    /**
     * Set year
     *
     * @param  integer $year
     * @return Book
     */
    public function setYear($year)
    {
        // TODO: Check if null!
        $this->year = $year;

        return $this;
    }

    /**
     * Get year
     *
     * @return integer
     */
    public function getYear()
    {
        return $this->year;
    }

    /**
     * TRUE if comments can be written about the Book
     * @var boolean $commentable
     *
     * @ORM\Column(type="boolean", nullable=false)
     */
    protected $commentable;

    /**
     * Set commentable
     *
     * @param  boolean $commentable
     * @return Book
     */
    public function setCommentable($commentable)
    {
        // TODO: Check if parameter is boolean!
        $this->commentable = $commentable;

        return $this;
    }

    /**
     * Get commentable
     *
     * @return boolean
     */
    public function isCommentable()
    {
        return $this->commentable;
    }

    /**
     * Collection of Users who would like to borrow a copy
     *
     * @var Doctrine\Common\Collections\ArrayCollection $wouldBorrow
     *
     * @ORM\ManyToMany(targetEntity="KekRozsak\SecurityBundle\Entity\User")
     * @ORM\JoinTable(name="book_would_borrow")
     */
    protected $wouldBorrow;

    /**
     * Add a user for want-to-borrowers
     *
     * @param  KekRozsak\SecurityBundle\Entity\User $user
     * @return Book
     */
    public function addWouldBorrow(User $user)
    {
        // TODO: Check if null!
        $this->wouldBorrow->add($user);

        return $this;
    }

    /**
     * Get wouldBorrow list
     *
     * @return Doctrine\Common\Collections\ArrayCollection
     */
    public function getWouldBorrow()
    {
        return $this->wouldBorrow;
    }

    /**
     * Check if $user would like to borrow this book
     *
     * @param  KekRozsak\SecurityBundle\Entity\User $user
     * @return boolean
     */
    public function userWouldBorrow(User $user)
    {
        return $this->wouldBorrow->contains($user);
    }

    /**
     * Collection of Users who would like to buy a copy of this book
     *
     * @var Doctrine\Common\Collections\ArrayCollection $wouldBuy
     *
     * @ORM\ManyToMany(targetEntity="KekRozsak\SecurityBundle\Entity\User")
     * @ORM\JoinTable(name="book_would_buy")
     */
    protected $wouldBuy;

    /**
     * Add a user for want-to-buyers
     *
     * @param  KekRozsak\SecurityBundle\Entity\User $user
     * @return Book
     */
    public function addWouldBuy(User $user)
    {
        $this->wouldBuy->add($user);

        return $this;
    }

    /**
     * Get wouldBuy list
     *
     * @return Doctrine\Common\Collections\ArrayCollection
     */
    public function getWouldBuy()
    {
        return $this->wouldBuy;
    }

    /**
     * Check if specified user would buy this book
     *
     * @param  KekRozsak\SecurityBundle\Entity\User $user
     * @return boolean
     */
    public function userWouldBuy(User $user)
    {
        return $this->wouldBuy->contains($user);
    }
}

src/KekRozsak/FrontBundle/Form/Type/BookType.php
<?php

namespace KekRozsak\FrontBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                    'author',
                    null,
                    array(
                        'label' => 'Szerző',
                    )
                )
            ->add(
                    'title',
                    null,
                    array(
                        'label' => 'Cím',
                    )
                )
            ->add(
                    'year',
                    null,
                    array(
                        'label' => 'Kiadás éve',
                    )
                )
            ->add(
                    'commentable',
                    null,
                    array(
                        'label'    => 'Kommentelhető?',
                        'required' => false
                    )
                )
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'KekRozsak\FrontBundle\Entity\Book'
        ));
    }

    public function getName()
    {
        return 'kekrozsak_frontbundle_booktype';
    }
}

src/KekRozsak/FrontBundle/Controller/BookController.php
<?php

namespace KekRozsak\FrontBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Response;

use KekRozsak\FrontBundle\Entity\Book;
use KekRozsak\FrontBundle\Entity\BookCopy;
use KekRozsak\FrontBundle\Form\Type\BookType;

class BookController extends Controller
{
    /**
     * @Route("/konyvtar/", name="KekRozsakFrontBundle_bookList", options={"expose" = true})
     * @Template()
     */
    public function listAction()
    {
        $query = $this
                ->getDoctrine()
                ->getManager()
                ->createQuery('
                    SELECT
                        b
                    FROM
                        KekRozsakFrontBundle:Book b
                    ORDER BY
                        b.author ASC,
                        b.title ASC,
                        b.year ASC
                ')
            ;

        $books = $query->getResult();

        return array(
            'books' => $books,
        );
    }

    /**
     * @Route("/konyvtar/uj-konyv.html", name="KekRozsakFrontBundle_bookNew", options={"expose" = true})
     * @Template()
     */
    public function newAction()
    {
        $book = new Book();
        $newBookForm = $this->createForm(new BookType(), $book);
        $request = $this->getRequest();

        if ($request->getMethod() == 'POST') {
            $newBookForm->bindRequest($request);
            if ($newBookForm->isValid()) {
                $em = $this->getDoctrine()->getManager();
                $em->persist($book);
                $em->flush();

                return new Response('success');
            }
        }

        return array(
            'form'  => $newBookForm->createView(),
        );
    }

    /**
     * @Route("/sugo/konyvtar-lista.html", name="KekRozsakFrontBundle_bookListHelp")
     * @Template()
     */
    public function listHelpAction()
    {
        return array();
    }

    /**
     * @param KekRozsak\FrontBundle\Entity\Book $book
     *
     * @Route("/konyvtar/{id}/adatok.{_format}", name="KekRozsakFrontBundle_bookAjaxData", defaults={"_format": "html"}, options={"expose": true})
     * @Template()
     * @ParamConverter("book")
     */
    public function ajaxDataAction(Book $book)
    {
        return array(
            'book' => $book,
        );
    }

    /**
     * @param KekRozsak\FrontBundle\Entity\Book $book
     *
     * @Route("/konyvtar/{id}/torol.do}", name="KekRozsakFrontBundle_bookDeleteCopy", requirements={"id": "\d+"}, options={"expose": true})
     * @ParamConverter("book")
     */
    public function ajaxDeleteBookAction(Book $book)
    {
        $copies = $book->getUsersCopies($this->get('security.context')->getToken()->getUser());
        $em = $this->getDoctrine()->getManager();
        $copies->forAll(function($key, $copy) use ($book, $em) {
            $book->removeCopy($copy);
            $em->remove($copy);
        });
        $em->persist($book);
        $em->flush();

        return new Response();
    }

    /**
     * @param KekRozsak\FrontBundle\Entity\Book $book
     *
     * @Route("/konyvtar/{id}/ujpeldany.do", name="KekRozsakFrontBundle_bookAddCopy", requirements={"id": "\d+"}, options={"expose": true})
     * @ParamConverter("book")
     */
    public function ajaxAddCopyAction(Book $book)
    {
        $user = $this->get('security.context')->getToken()->getUser();
        $copies = $book->getUsersCopies($user);
        if ($copies->count() == 0) {
            $copy = new BookCopy($book, $user);
            $em = $this->getDoctrine()->getManager();
            $em->persist($copy);
            $em->flush();
        }

        return new Response();
    }

    /**
     * @param KekRozsak\FrontBundle\Entity\Book $book
     * @param boolean                           $newValue
     *
     * @Route("/konyvtar/{id}/kolcsonozheto.do/{newValue}", name="KekRozsakFrontBundle_bookSetCopyBorrowable", requirements={"id": "\d+"}, options={"expose": true})
     * @ParamConverter("book")
     */
    public function ajaxSetBookCopyBorrowableAction(Book $book, $newValue)
    {
        $user = $this->get('security.context')->getToken()->getUser();
        $copies = $book->getUsersCopies($user);
        $em = $this->getDoctrine()->getManager();
        $copies->forAll(function($key, $copy) use ($em, $newValue) {
            $copy->setBorrowable($newValue);
            $em->persist($copy);
        });
        $em->flush();

        return new Response();
    }

    /**
     * @param KekRozsak\FrontBundle\Entity\Book $book
     * @param boolean                           $newValue
     *
     * @Route("/konyvtar/{id}/megveheto.do/{newValue}", name="KekRozsakFrontBundle_bookSetCopyForSale", requirements={"id": "\d+"}, options={"expose": true})
     * @ParamConverter("book")
     */
    public function ajaxSetBookCopyForSaleAction(Book $book, $newValue)
    {
        $user = $this->get('security.context')->getToken()->getUser();
        $copies = $book->getUsersCopies($user);
        $em = $this->getDoctrine()->getManager();
        $copies->forAll(function($key, $copy) use ($em, $newValue) {
            $copy->setBuyable($newValue);
            $em->persist($copy);
        });
        $em->flush();

        return new Response();
    }

    /**
     * @param KekRozsak\FrontBundle\Entity\Book $book
     * @param boolean                           $wantToBuy
     *
     * @Route("/konyvtar/{id}/szeretnek.do/{wantToBuy}", name="KekRozsakFrontBundle_bookWantOne", requirements={"id": "\d+"}, options={"expose": true})
     * @ParamConverter("book")
     */
    public function ajaxWantABookAction(Book $book, $wantToBuy)
    {
        $user = $this->get('security.context')->getToken()->getUser();

        if ($wantToBuy) {
            $book->addWouldBuy($user);
        } else {
            $book->addWouldBorrow($user);
        }

        $em = $this->getDoctrine()->getManager();
        $em->persist($book);
        $em->flush();

        return new Response();
    }
}

src/KekRozsak/FrontBundle/Resources/views/Book/ajaxData.html.twig
{# vim: ft=htmljinja
#}
<p>
    <strong>Szerző:</strong> {{ book.author }}<br />
    <strong>Cím:</strong> {{ book.title }}<br />
    <strong>Kiadás éve:</strong> {{ book.year }}<br />
</p>
<p>
    Nekem van <strong>{{ book.usersCopies(app.user)|length }}</strong>, ebből kölcsön van adva <strong>X</strong>.<br />
    A teljes közösségnek összesen <strong>{{ book.copies|length }}</strong> példánya van.<br />
    Kölcsönkérhető <strong>{{ book.copiesBorrowable|length }}</strong> példány, ebből <strong>{{ book.copiesBorrowedByUser(app.user)|length }}</strong> nálam van.<br />
</p>
<p>
{% if book.usersCopies(app.user)|length == 0 %}
    <span class="gomb add-copy-button" id="add-copy-button-{{ book.id }}">[Nekem is van egy]</span>
{% else %}
    <span class="gomb delete-copy-button" id="delete-copy-button-{{ book.id }}">[Nincs már]</span>
{# TODO
    <span class="gomb">[Eladtam valakinek a körben]</span>
#}
{% if book.usersCopiesBorrowable(app.user)|length == 0 %}
    <span class="gomb mine-is-borrowable-button" id="mine-is-borrowable-button-{{ book.id }}">[Az enyém is kölcsönkérhető]</span>
{% else %}
    <span class="gomb mine-is-not-borrowable-button" id="mine-is-not-borrowable-button-{{ book.id }}">[Nem szeretném kölcsönadni]</span>
{% endif %}
{% endif %}

{% if book.usersCopies(app.user)|length > 0 %}
{% if book.usersCopiesBuyable(app.user)|length == 0 %}
    <span class="gomb mine-is-for-sale-button" id="mine-is-for-sale-button-{{ book.id }}">[Az enyém eladó]</span>
{% else %}
    <span class="gomb mine-is-not-for-sale-button" id="mine-is-not-for-sale-button-{{ book.id }}">[Nem szeretném eladni]</span>
{% endif %}
{% endif %}

{% if book.copiesBorrowedByUser(app.user)|length == 0 and book.usersCopies(app.user)|length == 0 and not book.userWouldBorrow(app.user) %}
    <span class="gomb want-to-borrow-button" id="want-to-borrow-button-{{ book.id }}">[Kérek egyet kölcsön]</span>
{% endif %}

{% if book.usersCopies(app.user)|length == 0 and not book.userWouldBuy(app.user) %}
    <span class="gomb want-to-buy-button" id="want-to-buy-button-{{ book.id }}">[Vennék egyet]</span>
{% endif %}
</p>
{% if book.wouldBuy|length > 0 %}
<p>
    Ők szeretnének egyet kölcsönkérni:<br />
    <ul>
{% for user in book.wouldBorrow %}
        <li>{{ user|userdataspan }}</li>
{% endfor %}
    </ul>
</p>
{% endif %}
{% if book.wouldBuy|length > 0 %}
<p>
    Ők szeretnének venni egyet:<br />
    <ul>
{% for user in book.wouldBuy %}
        <li>{{ user|userdataspan }}</li>
{% endfor %}
    </ul>
</p>
{% endif %}

src/KekRozsak/FrontBundle/Resources/views/Book/list.html.twig
{# vim: ft=htmljinja
#}
{% extends 'KekRozsakFrontBundle:Default:main_template.html.twig' %}

{% block title %} - Könyvtár{% endblock %}

{% block buttonlist %}
<span class="gomb new-book-button">[Új könyv]</span>
{% if books|length > 0 %}
[Saját könyveim]
[Nálam lévő kölcsönzött könyvek]
{% endif %}
{% endblock buttonlist %}

{% block content %}
<h3>Könyvtár</h3>
{{ block('buttonlist') }}
{% if books|length > 0 %}
<table id="book-list">
    <thead>
        <tr>
            <td>Szerző</td>
            <td>Cím</td>
            <td>Év</td>
            <td>Összes</td>
            <td>Kölcsönözhető</td>
            <td>Saját</td>
            <td>Nálam (Vissza)</td>
        </tr>
    </thead>
    <tbody>
{% for book in books %}
        <tr class="book-row popup-opener {{ cycle(['odd', 'even'], loop.index0) }}" id="book-{{ book.id }}">
            <td class="popup-opener">{{ book.author }}</td>
            <td>{{ book.title }}</td>
            <td>{{ book.year }}</td>
            <td>{{ book.copies|length }}</td>
            <td>{{ book.copiesBorrowable|length }}</td>
            <td>{{ book.usersCopies(app.user)|length }}</td>
            <td>{{ book.copiesBorrowedByUser(app.user)|length }} ({{ book.copiesBorrowedReturnedByUser(app.user)|length }})</td>
        </tr>
{% endfor %}
    </tbody>
</table>
{{ block('buttonlist') }}
{% endif %}
{% endblock content %}

{% block bottomscripts %}
<script type="text/javascript">
$('.book-row').click(function() {
    bookid = 0;
    if (!$(this).attr('id').match(/^book-\d+$/)) {
        return false;
    }
    bookid = $(this).attr('id').replace(/^book-/, '');
    bookUrl = Routing.generate('KekRozsakFrontBundle_bookAjaxData', { id: bookid, _format: 'html' });
    bookCallback = function()
    {
        // TODO: Change alert() calls to HTML flashes
        $('.delete-copy-button').click(function()
        {
            bookid = 0;
            if (!$(this).attr('id').match(/^delete-copy-button-\d+$/)) {
                return false;
            }

            bookid = $(this).attr('id').replace(/^delete-copy-button-/, '');
            url = Routing.generate('KekRozsakFrontBundle_bookDeleteCopy', { id: bookid });
            $.ajax({
                method: 'GET',
                url:    url
            }).done(function()
            {
                doPopup('', 'Betöltés...', bookUrl, 400, 300, bookCallback);
            }).error(function()
            {
                // TODO: Make this a flash!
                alert('Nem sikerült törölni');
            });
        });

        $('.add-copy-button').click(function()
        {
            bookid = 0;
            if (!$(this).attr('id').match(/^add-copy-button-\d+$/)) {
                return false;
            }
            bookid = $(this).attr('id').replace(/^add-copy-button-/, '');
            url = Routing.generate('KekRozsakFrontBundle_bookAddCopy', { id: bookid });
            $.ajax({
                method: 'GET',
                url:    url
            }).done(function()
            {
                doPopup('', 'Betöltés...', bookUrl, 400, 300, bookCallback);
            }).error(function()
            {
                // TODO: Make this a flash!
                alert('Nem sikerült bejegyezni ezt a példányt');
            });
        });

        $('.mine-is-borrowable-button, .mine-is-not-borrowable-button').click(function()
        {
            bookid = 0;
            if (!$(this).attr('id').match(/^mine-is-(not-)?borrowable-button-\d+$/)) {
                return false;
            }
            isBorrowable = ($(this).attr('id').match(/^mine-is-not-borrowable-button-\d+$/)) ? 0 : 1;
            bookid = $(this).attr('id').replace(/^mine-is-(not-)?borrowable-button-/, '');
            url = Routing.generate('KekRozsakFrontBundle_bookSetCopyBorrowable', { id: bookid, newValue: isBorrowable });
            $.ajax({
                method: 'GET',
                url:    url
            }).done(function()
            {
                doPopup('', 'Betöltés...', bookUrl, 400, 300, bookCallback);
            }).error(function()
            {
                // TODO: Make this a flash!
                alert('Nem sikerült bejegyezni ezt a példányt');
            });
        });

        $('.mine-is-for-sale-button, .mine-is-not-for-sale-button').click(function()
        {
            bookid = 0;
            if (!$(this).attr('id').match(/^mine-is-(not-)?for-sale-button-\d+$/)) {
                return false;
            }
            isForSale = ($(this).attr('id').match(/^mine-is-not-for-sale-button-\d+$/)) ? 0 : 1;
            bookid = $(this).attr('id').replace(/^mine-is-(not-)?for-sale-button-/, '');
            url = Routing.generate('KekRozsakFrontBundle_bookSetCopyForSale', { id: bookid, newValue: isForSale });
            $.ajax({
                method: 'GET',
                url:    url
            }).done(function()
            {
                doPopup('', 'Betöltés...', bookUrl, 400, 300, bookCallback);
            }).error(function()
            {
                // TODO: Make this a flash!
                alert('Nem sikerült bejegyezni ezt a példányt');
            });
        });

        $('.want-to-buy-button, .want-to-borrow-button').click(function()
        {
            bookid = 0;
            if (!$(this).attr('id').match(/^want-to-(buy|borrow)-button-\d+$/)) {
                return false;
            }
            toBuy = ($(this).attr('id').match(/^want-to-buy-button-\d+$/)) ? 1 : 0;
            bookid = $(this).attr('id').replace(/^want-to-(buy|borrow)-button-/, '');
            url = Routing.generate('KekRozsakFrontBundle_bookWantOne', { id: bookid, wantToBuy: toBuy });
            $.ajax({
                type: 'GET',
                url:  url
            }).done(function()
            {
                doPopup('', 'Betöltés...', bookUrl, 400, 300, bookCallback);
            }).error(function()
            {
                alert('Nem sikerült bejegyezni a kérést');
            });
        });
    };

    doPopup('', 'Betöltés...', bookUrl, 400, 300, bookCallback);
});

function setupAjaxBookForm()
{
    $('#new-book-form').ajaxForm({
        target:        '#new-book-form-result',
        replaceTarget: true,
        success:       function(data) {
            if (data == 'success') {
                // TODO: Reload the book list with an AJAX request instead of
                // reloading the page.
                window.location = Routing.generate('KekRozsakFrontBundle_bookList');
            }
        }
    });
}

$('.new-book-button').click(function() {
    creatorUrl = Routing.generate('KekRozsakFrontBundle_bookNew');
    doPopup('Új könyv', 'Betöltés...', creatorUrl, 500, 400, setupAjaxBookForm);
});

$('#new-book-form').on('submit', function(e) {
    e.preventDefault();

    $(this).ajaxSubmit({
        target:        '#new-book-form-result',
        replaceTarget: true
    });
});
</script>
{% endblock bottomscripts %}

src/KekRozsak/FrontBundle/Resources/views/Book/listHelp.html.twig
<p>
    A könyvek részletes adatait a szerzőre, címre vagy a kiadás évére kattintva
    tudhatod meg. Az ekkor felbukkanó ablakban tudod bejelölni, ha neked is van
    egy példányod, vagy ha pl. szeretnél kölcsönkérni egyet.
<p>

src/KekRozsak/FrontBundle/Resources/views/Book/new.html.twig
{% form_theme form 'KekRozsakFrontBundle:Form:user_form.html.twig' %}
<div id="new-book-form-result">
    <form method="POST" action="{{ path('KekRozsakFrontBundle_bookNew') }}" id="new-book-form">
        <table>
            {{ form_widget(form) }}
        </table>
        <button id="new-book-save-button" type="submit">Mentés</button>
    </form>
</div>